addSbtPlugin("com.github.gseitz" % "sbt-protobuf" % "0.6.5")
// TODO: switch to addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
// This version is ancient and not supported
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("com.github.sbt" % "sbt-findbugs" % "2.0.0")
addSbtPlugin("io.shiftleft" % "sbt-ci-release-early" % "2.0.18")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"   % "1.3.5")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.27")
addSbtPlugin("io.shiftleft" % "sbt-overflowdb" % "2.27")
