openapi: 3.0.0
info:
  title: CPG API
  description: An API that allows users to create and perform queries on CPGs.
  version: 1.0.0
oop:
paths:
  /docs:
    get:
      summary: Display this documentation page.
      tags:
        - Documentation
      responses:
        '200':
          description: Documentation has loaded successfully.
  /swagger.yml:
    get:
      summary: Retrieve the documentation in OpenAPI YAML format.
      tags:
        - Documentation
      responses:
        '200':
          description: Documentation has loaded successfully.

  /v1/create:
    post:
      summary: Create a new CPG from a set of files.
      tags:
        - CPG Creation
      consumes:
        - application/json
      parameters:
        - in: body
          schema:
            $ref: '#/components/schemas/CPGCreate'
      responses:
        '201':
          description: A job to create the CPG has been scheduled.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CPGResourceCreatedResponse'
        '400':
          description: One or more of the specified files could not be found.
          content:
            application/json:
              schema:
                $ref: '#components/schemas/APIError'
  /v1/cpg/{uuid}:
    get:
      summary: Retrieve the status of a CPG creation.
      tags:
        - CPG Creation
      parameters:
        - in: path
          description: A UUID referring to a CPG.
          schema:
            type: uuid
      responses:
        '200':
          description: The status of the CPG, along with an optional error message if something went wrong.
          content:
            applicaton/json:
              schema:
                $ref: '#/components/schemas/CPGJobCompleteResponse'
  /v1/cpg/{uuid}/query:
    post:
      summary: Run a query against the specified CPG.
      tags:
        - CPG Queries
      parameters:
        - in: path
          description: A UUID referring to a CPG.
          schema:
            type: uuid
        - in: body
          schema:
            $ref: '#/components/schemas/CPGQueryCreate'
      responses:
        '201':
          description: The query has been successfully scheduled.
          content:
            application/json:
              schema:
                $ref: '#components/schemas/CPGResourceCreatedResponse'
        '404':
          description: The referenced CPG was not found.
          content:
            application/json:
              schema:
                $ref: '#components/schemas/APIError'
        '422':
          description: There was an error when creating the referenced CPG.
          content:
            application/json:
              schema:
                $ref: '#components/schemas/APIError'
  /v1/query/{uuid}:
    get:
      summary: Retrieve the result of a CPG query.
      tags:
        - CPG Queries
      parameters:
        - in: path
          description: A UUID referring to a CPG query.
          schema:
            type: uuid
      responses:
        '200':
          description: The result of the CPG query, or an error message if the query failed.
          content:
            applicaton/json:
              schema:
                $ref: '#/components/schemas/CPGJobCompleteResponse'

tags:
  - name: Documentation
    description: Endpoints used to access documentation.
  - name: CPG Creation
    description: Endpoints used to create CPGs.
  - name: CPG Queries
    description: Endpoints used to perform queries on CPGs.

components:
  schemas:
    CPGCreate:
      type: object
      required:
        - files
      properties:
        files:
          type: array
          items:
            type: string
          example: ["/path/to/some/file"]
    CPGQueryCreate:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          example: "cpg.method.l"
    CPGResourceCreatedResponse:
      type: object
      required:
        - uuid
      properties:
        uuid:
          type: string
          format: uuid
          example: '2bdecd0c-870f-4aad-bb1b-4af5daf758c3'
    CPGJobCompleteResponse:
      type: object
      required:
        - ready
      properties:
        ready:
          type: boolean
          example: true
        result:
          type: string
          description: A nested object or string indicating the result.
          example: "A string result"
        error:
          type: string
          example: "Something has gone horribly wrong!"
    APIError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "Error content."