#!/usr/bin/env python3

import argparse

class JoernCreate:

    def main(self):

        parser = argparse.ArgumentParser(description='Instruct server to create a CPG')
        parser.add_argument('directories', type=str, nargs='+',
                    help='directories containing C/C++ code')
        parser.add_argument('--name', dest='cpg_name', action='store',
                    default="cpg.bin.zip",
                    help='Name of the CPG')
        args = parser.parse_args()

if __name__ == '__main__':
    JoernCreate().main()
