Name: Build codepropertygraph

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    matrix:
      strategy:
        - { version: "2.13.0", binary-version: "2.13" }

  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run sbt tests
      run: sbt scalafmtCheck test
    - name: Run fuzzypp tests
      run: cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 ./fuzzypp
      run: cmake --build . --config Release
      run: ./fuzzypp/bin/fuzzyppcli-tests
