Name: Build codepropertygraph

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run sbt tests
      run: sbt scalafmtCheck test
    - name: Run fuzzypp tests
      run: cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 ./fuzzypp
      run: cmake --build . --config Release
      run: ./fuzzypp/bin/fuzzyppcli-tests
